name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: ./dispatcher
      run: go get -v -t -d

    - name: Build
      working-directory: ./dispatcher
      run: go build -v .

    - name: Test
      working-directory: ./dispatcher
      run: go test -v -covermode=count -coverprofile=profile.cov

    - name: Publish Test Results to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./dispatcher/profile.cov"
