name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: ./dispatcher
      run: go get -v -t -d

    - name: Build
      working-directory: ./dispatcher
      run: go build -v .

    - name: Test
      working-directory: ./dispatcher
      run: go test -v -covermode=count -coverprofile=profile.cov

    - name: Send test results to coveralls
      working-directory: ./dispatcher
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go get -u github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
